# 植物识别系统配置文件

# 服务器配置
server:
  host: "0.0.0.0"
  port: 5000
  debug: true
  secret_key: "your-secret-key-here"
  max_content_length: 16777216  # 16MB

# 文件上传配置
upload:
  folder: "uploads"
  allowed_extensions: ["png", "jpg", "jpeg", "gif", "bmp"]
  max_file_size: 16777216  # 16MB

# 植物识别配置
plant_identification:
  model_path: "plantid/models/quarrying_plantid_model.onnx"
  label_map_path: "plantid/models/quarrying_plantid_label_map.txt"
  family_name_map_path: "plantid/models/family_name_map.json"
  genus_name_map_path: "plantid/models/genus_name_map.json"
  default_topk: 5
  confidence_threshold: 0.1

# 图像处理配置
image_processing:
  resize_short: 224
  crop_size: 224
  normalize_mean: [0.485, 0.456, 0.406]
  normalize_std: [0.229, 0.224, 0.225]
  max_display_size: 1080

# 日志配置
logging:
  level: "INFO"
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  file: "logs/app.log"
  max_bytes: 10485760  # 10MB
  backup_count: 5

# 缓存配置
cache:
  enabled: true
  ttl: 3600  # 1小时
  max_size: 1000

# 性能配置
performance:
  batch_size: 10
  max_workers: 4
  gpu_enabled: false

# API配置
api:
  rate_limit: 100  # 每分钟请求数
  timeout: 30  # 秒
  cors_enabled: true
  cors_origins: ["*"]

# 数据库配置（可选）
database:
  enabled: false
  type: "sqlite"
  path: "data/plantid.db"

# 监控配置
monitoring:
  enabled: true
  metrics_port: 9090
  health_check_interval: 60  # 秒 